### ISSUE TITLE
Publish CircleCI Orb - Testing for Selenium

### ISSUE THREAD

**Issue by napoles-mk** [muuklabs/circleci-orb#9]

**Comment by napoles-mk** [comment]
New major version (2.0.0) of CircleCi Orb has been published: https://circleci.com/developer/orbs/orb/muuklabs/muuktest

We have two jobs to support PW and MKCLI (Selenium) executions.

MKCLI example:
```
version: '2.1'
orbs:
  muuktest: muuklabs/muuktest@2.0.0
workflows:
  execute:
    jobs:
      - muuktest/mkcli:
          muuk_key: MUUK_KEY
          t: TC0001
```

Playwright example:
```
version: '2.1'
orbs:
  muuktest: muuklabs/muuktest@2.0.0
workflows:
  execute:
    jobs:
      - muuktest/mkpw:
          muuk_key: MUUK_KEY
          p: hashtag
          t: deployment
```

See the circleci orb page for more details: https://circleci.com/developer/orbs/orb/muuklabs/muuktest
